Repository zapier/zapier-platform, pull requests merged in 2025-09, with the labels that each got.

#1093 feat(schema, cli) Support version with label [PDE-6384]
  packages/cli/src/oclif/ZapierBaseCommand.js
  packages/core/types/schemas.generated.d.ts
  packages/schema/docs/build/schema.md
  packages/schema/exported-schema.json
  packages/schema/lib/schemas/VersionSchema.js
Labels: team-dev-platform, needs-review

#1145 chore(cli): Update `zapier pull` description to clarify it pulls production version, not latest, for public integrations (PDE-6517)
  packages/cli/docs/cli.md
  packages/cli/src/oclif/commands/pull.js
Labels: team-dev-platform

#1147 PDE-6429 fix(core): censor sensitive info in `ResponseError`
  packages/cli/docs/cli.md
  packages/cli/src/tests/utils/build.js
  packages/core/src/http-middlewares/after/prepare-response.js
  packages/core/src/tools/create-logger.js
  packages/core/src/tools/secret-scrubber.js
  packages/core/test/http-middleware.js
Labels: needs-review

#1152 PDE-5956: revert(cli): revert `zapier migrate --action` feature
  packages/cli/docs/cli.md
  packages/cli/src/oclif/commands/migrate.js
Labels: needs-review

#1153 feat(schema): add skipCleanArrayInputData option to actions ( PDE-6533 )
  packages/core/types/schemas.generated.d.ts
  packages/schema/docs/build/schema.md
  packages/schema/exported-schema.json
  packages/schema/lib/schemas/BasicActionOperationSchema.js
  packages/schema/lib/schemas/BasicHookOperationSchema.js
  packages/schema/lib/schemas/BasicHookToPollOperationSchema.js
  packages/schema/lib/schemas/BasicOperationSchema.js
  packages/schema/lib/schemas/BasicPollingOperationSchema.js
  packages/schema/lib/schemas/BasicSearchOperationSchema.js
Labels: needs-review

#1154 PDE-6429 chore: release 17.7.1
  CHANGELOG.md
  example-apps/babel/package.json
  example-apps/basic-auth-typescript/package.json
  example-apps/basic-auth/package.json
  example-apps/callback/package.json
  example-apps/create/package.json
  example-apps/custom-auth-typescript/package.json
  example-apps/custom-auth/package.json
  example-apps/digest-auth-typescript/package.json
  example-apps/digest-auth/package.json
  example-apps/dynamic-dropdown/package.json
  example-apps/files/package.json
  example-apps/github/package.json
  example-apps/middleware/package.json
  example-apps/minimal-esm/package.json
  example-apps/minimal/package.json
  example-apps/oauth1-trello-typescript/package.json
  example-apps/oauth1-trello/package.json
  example-apps/oauth1-tumblr/package.json
  example-apps/oauth1-twitter/package.json
  example-apps/oauth2-typescript/package.json
  example-apps/oauth2/package.json
  example-apps/onedrive/package.json
  example-apps/openai/package.json
  example-apps/resource/package.json
  example-apps/rest-hooks/package.json
  example-apps/search-or-create/package.json
  example-apps/search/package.json
  example-apps/session-auth-typescript/package.json
  example-apps/session-auth/package.json
  example-apps/trigger/package.json
  packages/cli/package.json
  packages/core/package.json
  packages/core/types/schemas.generated.d.ts
  packages/schema/docs/build/schema.md
  packages/schema/exported-schema.json
  packages/schema/package.json
Labels: needs-review

#1162 chore(core): Add Input Field inference for parent, dict, and list fields
  packages/core/types/inputs.d.ts
  packages/core/types/inputs.plainfields.test-d.ts
  packages/core/types/inputs.test-d.ts
Labels: needs-review

#1164 chore(core): Add `choice` field hints to bundle inputs
  packages/core/types/inputs.d.ts
  packages/core/types/inputs.plainfields.test-d.ts
  packages/core/types/inputs.test-d.ts
Labels: needs-review

#1166 core(fix): Allow paging_token with undefined as a value
  packages/core/src/checks/search-is-array-or-envelope.js
  packages/core/test/checks.js
Labels: needs-review

#1169 PDE-6592 docs(cli): fix incorrect docs in `zapier migrate`
  packages/cli/docs/cli.md
  packages/cli/src/oclif/commands/migrate.js
Labels: needs-review

#1170 PDE-6592 test(core): fix failing tests due to HttpBin URL change
  packages/core/test/create-app.js
  packages/core/test/create-request-client.js
  packages/core/test/http-middleware.js
  packages/core/test/request-client-internal.js
  packages/legacy-scripting-runner/test/integration-test.js
Labels: needs-review
