Repository zapier/zapier-platform, pull requests merged in 2025-05, with the labels that each got.

#1020 fix(core): Fix CLI v16 and Core v17 incompatibility [PDE-6131]
  packages/cli/src/version-store.js
  packages/core/src/tools/create-lambda-handler.js
Labels: team-dev-platform, needs-review

#1021 chore(cli, core, schema): Release 17.0.1 [PDE-6131]
  CHANGELOG.md
  example-apps/babel/package.json
  example-apps/basic-auth/package.json
  example-apps/callback/package.json
  example-apps/create/package.json
  example-apps/custom-auth/package.json
  example-apps/digest-auth/package.json
  example-apps/dynamic-dropdown/package.json
  example-apps/files/package.json
  example-apps/github/package.json
  example-apps/middleware/package.json
  example-apps/minimal-esm/package.json
  example-apps/minimal/package.json
  example-apps/oauth1-trello/package.json
  example-apps/oauth1-tumblr/package.json
  example-apps/oauth1-twitter/package.json
  example-apps/oauth2/package.json
  example-apps/onedrive/package.json
  example-apps/openai/package.json
  example-apps/resource/package.json
  example-apps/rest-hooks/package.json
  example-apps/search-or-create/package.json
  example-apps/search/package.json
  example-apps/session-auth/package.json
  example-apps/trigger/package.json
  example-apps/typescript-esm/package.json
  example-apps/typescript/package.json
  packages/cli/package.json
  packages/core/package.json
  packages/core/types/schemas.generated.d.ts
  packages/schema/docs/build/schema.md
  packages/schema/exported-schema.json
  packages/schema/package.json
Labels: team-dev-platform, needs-review

#1024 PDE-6136 - fix(cli) - Fix Path for windows
  packages/cli/src/utils/build.js
  packages/cli/src/utils/local.js
Labels: team-dev-platform

#1032 PDE-6149 fix(core): internalize flag that enables/disable `{{curlies}}` replacement, disable `{{curlies}}` for Raw Requests
  packages/core/src/constants.js
  packages/core/src/execute-request.js
  packages/core/src/execute.js
  packages/core/src/http-middlewares/before/inject-input.js
  packages/core/src/http-middlewares/before/prepare-request.js
  packages/core/src/tools/cleaner.js
  packages/core/src/tools/request-merge.js
  packages/core/test/create-app.js
  packages/core/test/create-request-client.js
  packages/core/test/execute-request.js
  packages/core/test/http-middleware.js
  packages/core/types/schemas.generated.d.ts
  packages/legacy-scripting-runner/index.js
  packages/legacy-scripting-runner/test/integration-test.js
  packages/legacy-scripting-runner/test/zfactory.js
Labels: team-dev-platform, needs-review

#1033 PDE-6151 fix(cli): "Cannot find base config file" tsconfig warning
  packages/cli/src/utils/build.js
Labels: needs-review

#1036 PDE-6125 chore: regenerate some `example-apps` and delete `examples` directory
  example-apps/oauth2/.gitignore
  example-apps/oauth2/package.json
  example-apps/typescript-esm/package.json
  example-apps/typescript-esm/src/authentication.ts
  example-apps/typescript-esm/src/index.ts
  example-apps/typescript-esm/src/test/creates.test.ts
  example-apps/typescript-esm/src/triggers/movie.ts
  example-apps/typescript/package.json
  example-apps/typescript/src/authentication.ts
  example-apps/typescript/src/index.ts
  example-apps/typescript/src/triggers/movie.ts
  examples/README.md
  examples/restHooks.js
Labels: needs-review

#1037 PDE-6149 fix(legacy-scripting-runner): ensure `z.request()` renders `{{curlies}}` on different core versions
  packages/legacy-scripting-runner/CHANGELOG.md
  packages/legacy-scripting-runner/index.js
  packages/legacy-scripting-runner/package.json
Labels: needs-review

#1034 PDE-6145 fix(core): `{{curlies}}` in `requestTemplate` should be replaced
  packages/core/src/http-middlewares/before/prepare-request.js
  packages/core/src/tools/cleaner.js
  packages/core/test/constants.js
  packages/core/test/create-request-client.js
  packages/core/test/http-middleware.js
Labels: needs-review

#1042 PDE-6176 fix(core): unexpected line break in logged response content
  packages/core/src/tools/create-http-patch.js
Labels: needs-review
