Repository zapier/zapier-platform, pull requests merged in 2025-06, with the labels that each got.

#1049 chore(cli, schema, core): Release 17.0.4 [PDE-6187]
  CHANGELOG.md
  example-apps/babel/package.json
  example-apps/basic-auth/package.json
  example-apps/callback/package.json
  example-apps/create/package.json
  example-apps/custom-auth/package.json
  example-apps/digest-auth/package.json
  example-apps/dynamic-dropdown/package.json
  example-apps/files/package.json
  example-apps/github/package.json
  example-apps/middleware/package.json
  example-apps/minimal-esm/package.json
  example-apps/minimal/package.json
  example-apps/oauth1-trello/package.json
  example-apps/oauth1-tumblr/package.json
  example-apps/oauth1-twitter/package.json
  example-apps/oauth2/package.json
  example-apps/onedrive/package.json
  example-apps/openai/package.json
  example-apps/resource/package.json
  example-apps/rest-hooks/package.json
  example-apps/search-or-create/package.json
  example-apps/search/package.json
  example-apps/session-auth/package.json
  example-apps/trigger/package.json
  example-apps/typescript-esm/package.json
  example-apps/typescript/package.json
  packages/cli/package.json
  packages/core/package.json
  packages/core/types/schemas.generated.d.ts
  packages/schema/docs/build/schema.md
  packages/schema/exported-schema.json
  packages/schema/package.json
Labels: team-dev-platform, needs-review

#1051 PDE-6200 chore: release 17.1.0
  CHANGELOG.md
  example-apps/babel/package.json
  example-apps/basic-auth/package.json
  example-apps/callback/package.json
  example-apps/create/package.json
  example-apps/custom-auth/package.json
  example-apps/digest-auth/package.json
  example-apps/dynamic-dropdown/package.json
  example-apps/files/package.json
  example-apps/github/package.json
  example-apps/middleware/package.json
  example-apps/minimal-esm/package.json
  example-apps/minimal/package.json
  example-apps/oauth1-trello/package.json
  example-apps/oauth1-tumblr/package.json
  example-apps/oauth1-twitter/package.json
  example-apps/oauth2/package.json
  example-apps/onedrive/package.json
  example-apps/openai/package.json
  example-apps/resource/package.json
  example-apps/rest-hooks/package.json
  example-apps/search-or-create/package.json
  example-apps/search/package.json
  example-apps/session-auth/package.json
  example-apps/trigger/package.json
  example-apps/typescript-esm/package.json
  example-apps/typescript/package.json
  packages/cli/docs/cli.md
  packages/cli/package.json
  packages/core/package.json
  packages/core/types/schemas.generated.d.ts
  packages/schema/docs/build/schema.md
  packages/schema/exported-schema.json
  packages/schema/package.json
Labels: needs-review

#1054 chore(core): PDE-6130 Release 17.2.0
  CHANGELOG.md
  example-apps/babel/package.json
  example-apps/basic-auth/package.json
  example-apps/callback/package.json
  example-apps/create/package.json
  example-apps/custom-auth/package.json
  example-apps/digest-auth/package.json
  example-apps/dynamic-dropdown/package.json
  example-apps/files/package.json
  example-apps/github/package.json
  example-apps/middleware/package.json
  example-apps/minimal-esm/package.json
  example-apps/minimal/package.json
  example-apps/oauth1-trello/package.json
  example-apps/oauth1-tumblr/package.json
  example-apps/oauth1-twitter/package.json
  example-apps/oauth2/package.json
  example-apps/onedrive/package.json
  example-apps/openai/package.json
  example-apps/resource/package.json
  example-apps/rest-hooks/package.json
  example-apps/search-or-create/package.json
  example-apps/search/package.json
  example-apps/session-auth/package.json
  example-apps/trigger/package.json
  example-apps/typescript-esm/package.json
  example-apps/typescript/package.json
  packages/cli/package.json
  packages/core/package.json
  packages/core/types/schemas.generated.d.ts
  packages/schema/docs/build/schema.md
  packages/schema/exported-schema.json
  packages/schema/package.json
Labels: needs-review

#1055 chore(core): PDE-6220 bump fernet to latest
  packages/core/package.json
  yarn.lock
Labels: needs-review

#1056 docs(cli) [PDE-6238] Update CLI Docs for new days before deprecation and sending emails
  packages/cli/docs/cli.md
  packages/cli/src/oclif/commands/deprecate.js
Labels: team-dev-platform

#1058 PDE-6249 fix(core): log `text/xml` response content, not just `application/xml`
  packages/core/src/tools/http.js
  packages/core/test/tools/create-http-patch.js
Labels: needs-review

#1062 [PDE-6273] Defensive when content-type is absent
  packages/core/src/tools/fetch-logger.js
Labels: needs-review

#1052 PDE-6175 feat(cli): faster `zapier build` and support for npm/yarn/pnpm workspaces
  .github/workflows/ci.yaml
  packages/cli/package.json
  packages/cli/src/constants.js
  packages/cli/src/oclif/commands/build.js
  packages/cli/src/oclif/commands/push.js
  packages/cli/src/tests/utils/build.js
  packages/cli/src/utils/build.js
  packages/cli/src/utils/files.js
  packages/cli/src/utils/ignore.js
  packages/cli/src/utils/itertools.js
  packages/cli/src/utils/misc.js
  yarn.lock
Labels: needs-review
